name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

env:
  PROJECT: DelugeClient
  IMAGE: deluge-core
  OWNER: connectjs
  TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Info
        run: docker info
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_HOST_DOMAIN }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker - Build
        run: docker build . --file ${{ env.PROJECT }}/Dockerfile --build-arg env=embedded --tag ${{ vars.DOCKER_HOST_DOMAIN }}/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.TAG }}
      - name: Docker - Push
        run: docker push ${{ vars.DOCKER_HOST_DOMAIN }}/${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.TAG }}
